runtime: nodejs18
instance_class: F1 # Instance class untuk App Engine Standard
env_variables:
  DB_USER: 'your-database-user'
  DB_PASSWORD: 'your-database-password'
  DB_NAME: 'your-database-name'
  INSTANCE_UNIX_SOCKET: '/cloudsql/your-connection-name'

  # vpc_access_connector:
  # name: projects/coba-443916/locations/us-central1/connectors/default

automatic_scaling:
  min_instances: 0
  max_instances: 2
  target_cpu_utilization: 0.65
  target_throughput_utilization: 0.5
