runtime: nodejs18
instance_class: F1 # Instance class untuk App Engine Standard
env_variables:
  DB_USER: 'root'
  DB_PASSWORD: '1234'
  DB_NAME: 'bioface_ui_db'
  INSTANCE_UNIX_SOCKET: '/cloudsql/coba-443916:us-central1:coba'

  # vpc_access_connector:
  # name: projects/coba-443916/locations/us-central1/connectors/default

automatic_scaling:
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.65
  target_throughput_utilization: 0.5
