runtime: nodejs18
service : bioface-userinteraction-api
env_variables:
  DB_USER: 'your_db_user'
  DB_PASSWORD: 'your_db_password'
  DB_NAME: 'your_db_name'
  DB_HOST: 'your_db_host'

vpc_access_connector:
  name: projects/<PROJECT_ID>/locations/<REGION>/connectors/<CONNECTOR_NAME>